Manorama Patil

43353

BE-11

information technology

 Insert the missing part of the code below to output "Hello World". __("Hello World"

In [1]:
print("Hello World")

Hello World

Find the mistake of programme if 5 > 2: print("Five is greater than two!")

In [3]:
if 5 > 2: 
 print("Five is greater than two!")

Five is greater than two!

Comments in Python are written with a special character, which one? This is a comment

In [ ]:
#Ans. The # character is used to write comments in python. 
#This is a comment

Use a multiline string to make the a multi line comment: This is a comment written in more that just one line

In [ ]:
"""This is a comment 
written in 
more that just one line"""

Create a variable named car and assign the value Volvo to it

In [4]:
car = "Volvo" 
car

'Volvo'

Create a variable named x and assign the value 50 to it.

In [5]:
x=50 
x

50

Display the sum of 5 + 10, using two variables: x and y.

In [7]:
x=5 
y=10 
print(x+y)

15

Create a variable called z, assign x + y to it, and display the result.

In [8]:
z=x+y 
print(z)

15

Insert the correct syntax to assign the same value to all three variables inone codeline.  x y z _ "Orange"

In [9]:
x=y=z="Orange"

Given a two integer numbers return their product and if the product isgreater than 1000, then return their sum
Given: number1 = 20number2 = 30 Expected Output: The result is 600 
Given: number1 = 40 number2 = 30 Expected Output: The result is 70

In [10]:
def fun(number1, number2): 
    mult = number1 * number2 
    if mult > 1000: 
        return number1 + number2 
    else: 
         return mult 
 
ans = fun(20, 30) 
print("The answer is->", ans) 
 
ans = fun(40, 30) 
print("The answer is->", ans)

The answer is-> 600
The answer is-> 70

 Reverse the following tuple  aTuple = (10, 20, 30, 40, 50)  Expected output: (50, 40, 30, 20, 10)

In [11]:
aTuple = (10, 20, 30, 40, 50) 
atuple = aTuple[::-1] 
atuple

(50, 40, 30, 20, 10)

 Access value 20 from the following tuple  aTuple = ("Orange", [10, 20, 30], (5, 15, 25)) Expected output: 20

In [12]:
aTuple = ("Orange", [10, 20, 30], (5, 15, 25)) 
aTuple[1][1]

20

 Given 2 strings, s1, and s2 return a new string made of the first, middleand last char each input string  Given: s1 = "America" s2 = "Japan" Expected Output: AJrpan

In [13]:
s1 = "America" 
s2 = "Japan" 
def fun1(s1,s2): 
    len1 = int(len(s1)/2) 
    len2 = int(len(s2)/2) 
    Str = s1[0] + s2[0] + s1[len1] + s2[len2] + s1[-1] + s2[-1] 
    return Str 
 
fun1(s1,s2)

'AJrpan'

 Given a Python list you should be able to display Python list in thefollowing order aLsit = [100, 200, 300, 400, 500] Expected output: [500, 400, 300, 200, 100]

In [14]:
aLsit = [100, 200, 300, 400, 500] 
aLsit = aLsit[::-1] 
print(aLsit)

[500, 400, 300, 200, 100]

 Concatenate two lists index-wise list1 = ["M", "na", "i", "Ke"]  list2 = ["y", "me", "s", "lly"] Expected output: ['My', 'name', 'is', 'Kelly']

In [15]:
List1 = ["M", "na", "i", "Ke"]  
List2 = ["y", "me", "s", "lly"] 
List3 = [i + j for i, j in zip(List1, List2)] # Sir, has told me to use zip function
print(List3)

['My', 'name', 'is', 'Kelly']

Given a two Python list. Iterate both lists simultaneously such that list1should display item in original order and list2 in reverse order list1 = [10, 20, 30, 40] list2 = [100, 200, 300, 400] Expected output: 10 40020 300 30 200 40 100

In [16]:
List1 = [10, 20, 30, 40] 
List2 = [100, 200, 300, 400] 
 
for l, m in zip(List1, List2[::-1]): # Sir, has told me to use zip function here 
    print(l, m)

10 400
20 300
30 200
40 100

Remove empty strings from the list of strings list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"] Expected output: ["Mike", "Emma", "Kelly", "Brad"]

In [18]:
List1 = ["Mike", "", "Emma", "Kelly", "", "Brad"] 
List2 = list(filter(None, List1))
print(List2)

['Mike', 'Emma', 'Kelly', 'Brad']

Write a Python program to display output in given format  
 
"""Twinkle, twinkle, little star, 
           How I wonder what you are!  
                   Up above the world so high,  
                   Like a diamond in the sky.  
Twinkle, twinkle, little star,  
           How I wonder what you are!"""

In [21]:
print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\t\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")

Twinkle, twinkle, little star,
	How I wonder what you are!
		Up above the world so high,
		Like a diamond in the sky.
Twinkle, twinkle, little star,
	How I wonder what you are!

 Write a Python program to display the first and last colors from thefollowing list. color_list = ["Red","Green","White" ,"Black"]

In [22]:
color_list = ["Red","Green","White" ,"Black"] 
print("First color:", color_list[0] + "\n" +"Last color:", color_list[-1])

First color: Red
Last color: Black